name: macOS CI

on: [push, pull_request]

jobs:
  macos:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: macos-26
            name: macOS 26 (Apple Silicon)

          - image: macos-15
            name: macOS 15 (Apple Silicon)

          - image: macos-15-intel
            name: macOS 15 (Intel)

    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies (via brew)
        run: |
          # Update brew to avoid installing robin-map manually
          # ref: https://github.com/Homebrew/homebrew-core/commit/bf0095fdd7e03bd3239afda4584951ee9305dc40
          brew update
          brew upgrade
          brew install catch2 boost-python3 nanobind pytest numpy

      - name: Configure project
        run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_PYTHON_BINDINGS=ON -DBUILD_TESTS=ON

      - name: Build project
        run: cmake --build build

      - name: Install project
        run: cmake --install build --prefix ./install

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
